### PR TITLE
[Braccio_Record_and_Replay] Show stop sign when joint enters dead zone.

### PR DESCRIPTION
**Pull request by aentinger**
When a joint is entering a dead zone (between 315° and 360°) the application is now showing a big stop sign which shall communicate to the user that he should unwind his latest operation. Joint recording is paused as long as a joint is in the invalid zone. As soon as the user turns the joint to be within a valid range again the stop sign disappears.

This prevents the issue that a user is surprised why a replayed sequence does not exactly mirror the recorded one, given that the joint was within the dead zone during some samples.

IMG_20220516_125454_015

### CODE REVIEW

**Comment by Esquirio** [comment]
@aentinger The image appears correctly in the Record mode, but only for the base and wrist roll movements. For the other joints, the stop image did not appear; is it correct?

**Comment by aentinger** [comment]
Yes, this is correct. The other joints have been mounted in such a way that is mechanically impossible for the user to move the servo into an invalid position.

**Review by Esquirio — APPROVED** [review]
The new feature, the stop sign, worked correctly. I still have problems with the Replay mode, but I will write a report on slack.

**Comment by aentinger** [comment]
@Esquirio Shall I align the example within the project tutorials too, i.e. copy over?

@clodpheasant On this topic (keeping the tutorials code-identical with the replay/record and manual control sketch in the top level `/examples` directory) I've been thinking ... why not keep the tutorial code as is ... which is easy to explain to newcomers and just keep the top-level examples as they are - basically keep them separate. This way there are two sketches to be used for demonstrating to new customers while keeping the code easy and the re-work of the content team at a minimum.

**Comment by aentinger** [comment]
I'll be merging this leaving the code within `Platform_Tutorials` unaligned for now, given there are still a couple of issues that need to be adressed.

**Comment by Esquirio** [comment]
I think yes, but first, it is necessary to check the issues with the Replay mode that I reported to you.

**Pull request merged**
