### PR TITLE
fix: updating the projects/tutorials codes

### PR DESCRIPTION
**Pull request by Esquirio**
Description of the changes in this branch:

- Updated one comment in the `examples/Braccio_Record_and_Replay/AppState.cpp` file.
- Updated all the code in the `examples/Platform_Tutorials/projects/p02-controlling-braccio-manually/01_Controlling_Manually_Braccio/` example. Now it is the same as the library example.
- Updated the challenge code in Project 02.
- Renamed project 03.
- Updated all the code in the `examples/Platform_Tutorials/projects/p03-record-replay-mode/01_Braccio_Record_and_Replay/` example. Now it is the same as the library example.
- Updated the challenge code in Project 03.

### CODE REVIEW

**Review by aentinger — APPROVED** [review]
LGTM :+1: Good to merge :+1: Do you need a new library release afterwards?

**Comment by Esquirio** [comment]
What did you mean by a new library release? New version number?

**Comment by aentinger** [comment]
> New version number?

Yes.

**Comment by aentinger** [comment]
Here you go: https://github.com/arduino-libraries/Arduino_Braccio_plusplus/releases/tag/1.3.2 . Now the latest changes are distributed via library manager too.

**Pull request merged**
