### PR TITLE
Braccio_Record_and_Replay: Fix video link/remove space.

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by facchinm** [comment]
May I suggest using asciicinema (https://asciinema.org/) instead than a video?

**Comment by aentinger** [comment]
> May I suggest using asciicinema (https://asciinema.org/) instead than a video?

Hi :coffee: :wave: I did not know about this. However, I thought that given the video is tiny (455 kB) its allright to serve it with the library. Frankly, we can also drop it, as it does not provide much additional value over the textual description. What do you think?

**Comment by facchinm** [comment]
Being already documented in the readme I think we can also drop it, but the last call is to the content team

**Comment by aentinger** [comment]
I don't think its the content teams call, the video was not made on the content teams request, it was merely I going the extra mile ... removing it.

**Pull request merged**
